# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/linux-64/_libgcc_mutex-0.1-main.conda
https://repo.anaconda.com/pkgs/main/linux-64/blas-1.0-mkl.conda
https://repo.anaconda.com/pkgs/main/linux-64/ca-certificates-2023.12.12-h06a4308_0.conda
https://conda.anaconda.org/nvidia/linux-64/cuda-cudart-11.8.89-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/cuda-cupti-11.8.87-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/cuda-nvrtc-11.8.89-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/cuda-nvtx-11.8.86-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ld_impl_linux-64-2.38-h1181459_1.conda
https://conda.anaconda.org/nvidia/linux-64/libcublas-11.11.3.6-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libcufft-10.9.0.58-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libcufile-1.7.2.10-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libcurand-10.3.3.141-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libcusolver-11.4.1.48-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libcusparse-11.7.5.86-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libgfortran5-11.2.0-h1234567_1.conda
https://conda.anaconda.org/nvidia/linux-64/libnpp-11.8.0.86-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libnvjpeg-11.9.0.86-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libstdcxx-ng-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/poppler-data-0.4.11-h06a4308_1.conda
https://conda.anaconda.org/pytorch/noarch/pytorch-mutex-1.0-cuda.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/tzdata-2023c-h04d1e81_0.conda
https://conda.anaconda.org/nvidia/linux-64/cuda-libraries-11.8.0-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libgfortran-ng-11.2.0-h00389a5_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgomp-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/_openmp_mutex-5.1-1_gnu.conda
https://conda.anaconda.org/nvidia/linux-64/cuda-runtime-11.8.0-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libgcc-ng-11.2.0-h1234567_1.conda
https://conda.anaconda.org/pytorch/linux-64/pytorch-cuda-11.8-h7e8668a_5.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/bzip2-1.0.8-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/c-ares-1.19.1-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/expat-2.5.0-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/freexl-1.0.6-h27cfd23_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/geos-3.8.0-he6710b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/giflib-5.2.1-h5eee18b_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/gmp-6.2.1-h295c915_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/icu-73.1-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jpeg-9e-h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/json-c-0.16-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lame-3.100-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lerc-3.0-h295c915_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libbrotlicommon-1.0.9-h5eee18b_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/libdeflate-1.17-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libev-4.33-h7f8727e_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libffi-3.4.4-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libiconv-1.16-h7f8727e_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libspatialindex-1.9.3-h2531618_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libtasn1-4.19.0-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libunistring-0.9.10-h27cfd23_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libuuid-1.41.5-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libwebp-base-1.3.2-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxcb-1.15-h7f8727e_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lz4-c-1.9.4-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ncurses-6.4-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/nspr-4.35-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/openh264-2.1.1-h4ff587b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/openssl-3.0.13-h7f8727e_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pcre-8.45-h295c915_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pixman-0.40.0-h7f8727e_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/qhull-2020.2-hdb19cb5_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/tbb-2021.8.0-hdb19cb5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/uriparser-0.9.7-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/xz-5.4.2-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.13-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/glib-2.69.1-he621ea3_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/hdf4-4.2.13-h3ca952b_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/hdf5-1.12.1-h2b7332f_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/intel-openmp-2023.1.0-hdb19cb5_46305.conda
https://repo.anaconda.com/pkgs/main/linux-64/libbrotlidec-1.0.9-h5eee18b_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/libbrotlienc-1.0.9-h5eee18b_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/libedit-3.1.20221030-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libidn2-2.3.4-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libkml-1.3.0-h096b73e_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/libnghttp2-1.57.0-h2d74bed_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libpng-1.6.39-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libssh2-1.10.0-hdbd6064_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxml2-2.10.4-hf1b16e4_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/mpfr-4.0.2-hb69a4c5_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/nettle-3.7.3-hbbd107a_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/pcre2-10.42-hebb0a14_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/readline-8.2-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tk-8.6.12-h1ccaba5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/xerces-c-3.2.4-h6a678d5_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/zstd-1.5.5-hc292b87_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/blosc-1.21.3-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/brotli-bin-1.0.9-h5eee18b_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/freetype-2.12.1-h4a9f257_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/gnutls-3.6.15-he1e5248_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/kealib-1.5.0-hd940352_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/krb5-1.20.1-h143b758_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libboost-1.82.0-h109eef0_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libtiff-4.5.1-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libzip-1.8.0-h6ac8c49_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-2023.1.0-h213fc3f_46343.conda
https://repo.anaconda.com/pkgs/main/linux-64/mpc-1.1.0-h10f8cd9_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/sqlite-3.41.2-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tiledb-2.3.3-h77177df_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/boost-cpp-1.82.0-hdb19cb5_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/brotli-1.0.9-h5eee18b_7.conda
https://conda.anaconda.org/pytorch/linux-64/ffmpeg-4.3-hf484d3e_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/fontconfig-2.14.1-h4c34cd2_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/lcms2-2.12-h3be6417_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libcurl-8.4.0-h251f7ec_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libnetcdf-4.8.1-h14805e7_4.conda
https://repo.anaconda.com/pkgs/main/linux-64/libpq-12.15-hdbd6064_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libwebp-1.3.2-h11a3e52_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/nss-3.89.1-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/openjpeg-2.4.0-h3ad879b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/proj-6.2.1-h05a3930_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/python-3.9.18-h955ad1f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/attrs-23.1.0-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cairo-1.16.0-hb05425b_5.conda
https://repo.anaconda.com/pkgs/main/linux-64/certifi-2024.2.2-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cfitsio-3.470-h5893167_7.conda
https://repo.anaconda.com/pkgs/main/noarch/charset-normalizer-2.0.4-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/click-8.1.7-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/curl-8.4.0-hdbd6064_0.conda
https://repo.anaconda.com/pkgs/main/noarch/cycler-0.11.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/dill-0.3.7-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/filelock-3.9.0-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/geotiff-1.7.0-h2a26cda_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/gmpy2-2.1.2-py39heeb90bb_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/idna-3.4-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/itsdangerous-2.0.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/joblib-1.2.0-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/kiwisolver-1.4.4-py39h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libspatialite-4.3.0a-h21ec0d7_23.conda
https://repo.anaconda.com/pkgs/main/linux-64/markupsafe-2.1.1-py39h7f8727e_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-service-2.4.0-py39h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/mpmath-1.3.0-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/munkres-1.1.4-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/networkx-3.1-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/packaging-23.1-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pillow-9.4.0-py39h6a678d5_1.conda
https://repo.anaconda.com/pkgs/main/noarch/pycparser-2.21-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyparsing-3.0.9-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyproj-2.6.1.post1-py39hb3025e9_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/pysocks-1.7.1-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/python-tzdata-2023.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pytz-2023.3.post1-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/rtree-1.0.1-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-68.0.0-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/six-1.16.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/noarch/threadpoolctl-2.2.0-pyh0d69192_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/typing_extensions-4.7.1-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/wheel-0.38.4-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/xyzservices-2022.9.0-py39h06a4308_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/zipp-3.11.0-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cffi-1.15.1-py39h5eee18b_3.conda
https://repo.anaconda.com/pkgs/main/noarch/click-plugins-1.1.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cligj-0.7.2-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/fonttools-4.25.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/importlib-metadata-6.0.0-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/importlib_resources-6.1.1-py39h06a4308_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/jinja2-3.1.2-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-base-1.25.2-py39hb5e798b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pip-23.2.1-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/poppler-22.12.0-h9614445_3.conda
https://repo.anaconda.com/pkgs/main/noarch/python-dateutil-2.8.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/sympy-1.11.1-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/werkzeug-2.2.3-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/branca-0.6.0-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/brotlipy-0.7.0-py39h27cfd23_1003.conda
https://repo.anaconda.com/pkgs/main/linux-64/cryptography-41.0.3-py39hdda0065_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/flask-2.2.2-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgdal-3.6.2-h01ceada_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyopenssl-23.2.0-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/urllib3-1.26.16-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/requests-2.31.0-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/bottleneck-1.3.7-py39ha9d4c09_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/contourpy-1.2.0-py39hdb19cb5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/folium-0.14.0-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/gdal-3.6.2-py39h0daa840_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-base-3.8.0-py39h1128e8f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_fft-1.3.8-py39h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_random-1.2.4-py39hdb19cb5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-1.25.2-py39h5f9d8c6_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numexpr-2.8.7-py39h85018f9_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/scipy-1.11.4-py39h5f9d8c6_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/shapely-2.0.1-py39h0fbb895_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/fiona-1.9.5-py39h1128e8f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pandas-2.2.1-py39h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/scikit-learn-1.3.0-py39h1128e8f_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/geopandas-base-0.12.2-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mapclassify-2.5.0-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/geopandas-0.12.2-py39h06a4308_0.conda
https://conda.anaconda.org/pytorch/linux-64/pytorch-2.0.1-py3.9_cuda11.8_cudnn8.7.0_0.tar.bz2
https://conda.anaconda.org/pytorch/linux-64/torchaudio-2.0.2-py39_cu118.tar.bz2
https://conda.anaconda.org/pytorch/linux-64/torchtriton-2.0.0-py39.tar.bz2
https://conda.anaconda.org/pytorch/linux-64/torchvision-0.15.2-py39_cu118.tar.bz2
